site:
  title: VSHN Application Catalog
  url: https://application-catalog.docs.vshn.ch
  start_page: ac::index.adoc
  keys:
    google_analytics: ''
content:
  sources:
  - url: .                 # The current folder is a git repo
    branches: HEAD         # "HEAD" uses whichever branch is currently checked out
    start_path: docs
    edit_url: 'https://git.vshn.net/vshn/application-catalog/edit/develop/{path}'
ui:
  bundle:

    url: https://github.com/vshn/antora-ui-default/releases/download/1.7/ui-bundle.zip

    snapshot: false
asciidoc:
  attributes:
    page-pagination: ''
    hide-uri-scheme: ''
    experimental: ''
    stem: ''
    icons: font
    kroki-server-url: https://vshn-kroki.appuioapp.ch
    kroki-fetch-diagram: ''
  extensions:
  - asciidoctor-kroki
output:
  destinations:
  - provider: fs
    path: ./_public
    clean: true

