name: Pull Request
on:
  pull_request:
    branches:
    - master

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Check Docs
      run: make check
    - name: No diff
      run: git diff --exit-code
